title: MATH 360
author: UBC Math
repository:
  url: https://github.com/UBCMath/MATH360
  branch: main
launch_buttons:
  jupyterhub_url: https://ubc.syzygy.ca/jupyter
  notebook_interface: "jupyterlab"
html:
  home_page_in_navbar: false
  use_repository_button: true
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# ghp-import -n -p -f _build/html