title: Introduction to Mathematical Modelling
author: UBC Math
repository:
  url: https://github.com/UBCMath/MATH360
  branch: main
launch_buttons:
  jupyterhub_url: https://ubc.syzygy.ca/jupyter
  notebook_interface: "jupyterlab"
html:
  home_page_in_navbar: false
  use_repository_button: true
  google_analytics_id: G-XWLESKW8XC
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
only_build_toc_files: true

# ghp-import -n -p -f _build/html